export const authTypes = {
    USER_LOADED: 'USER_LOADED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT: 'LOGOUT',
    EMAIL_VERIFIED: 'EMAIL_VERIFIED',
    USER_NOT_LOADED: 'USER_NOT_LOADED',
    ADD_REMOVE_FAVID: 'ADD_REMOVE_FAVID',
    ADD_REMOVE_SFX_FAVID: 'ADD_REMOVE_SFX_FAVID',
};
